dist: trusty
sudo: required
language: csharp
solution: CoreCRM.sln
mono: none
dotnet: 1.0.0-preview2-003131
install:
  - dotnet restore CoreCRM
  - dotnet restore CoreCRM.IntegrationTest
script:
  - dotnet test CoreCRM.IntegrationTest
