language: csharp
matrix:
    include:
        - os: linux
          sudo: required
          dist: trusty
          solution: CoreCRM.sln
          mono: none
          dotnet: 1.0.0-preview2-003131
        - os: osx
          solution: CoreCRM.sln

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install dotnet; fi
install:
  - dotnet restore CoreCRM
  - dotnet restore CoreCRM.IntegrationTest
script:
  - dotnet test CoreCRM.IntegrationTest
