language: csharp
matrix:
  include:
    - os: osx
      mono: none
      dotnet: 1.0.0-preview2-003131
      before_install:
        - brew install openssl
        - brew unlink openssl
        - brew link --force openssl
install:
  - dotnet restore CoreCRM
  - dotnet restore CoreCRM.IntegrationTest
script:
  - dotnet test CoreCRM.IntegrationTest
