language: csharp
matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      mono: none
      dotnet: 1.0.1
    - os: linux
      dist: trusty
      mono: none
      dotnet: 1.0.1

install:
  - ulimit -n 2048
  - dotnet restore
script:
  - ulimit -n 2048
  - dotnet test ./Tests/UnitTests/UnitTests.csproj
