language: csharp
matrix:
  include:
    - os: osx
      osx_image: xcode8.2
      mono: none
      dotnet: 1.0.0-preview2-003131
      before_install:
        - brew install openssl
        - ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/
        - ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/
        - brew unlink openssl
        - brew link --force openssl
install:
  - dotnet restore CoreCRM
  - dotnet restore CoreCRM.IntegrationTest
script:
  - dotnet test CoreCRM.IntegrationTest
