version: 0.1.{build}
os: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
configuration: Debug
platform: Any CPU
init:
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: appveyor-retry dotnet restore -v Minimal
build:
  project: CoreCRM.sln
  verbosity: minimal
cache:
  - '%USERPROFILE%\.nuget\packages'
deploy: off
