version: 0.1.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
configuration: Debug
platform: Any CPU
init:
- cmd: git config --global core.autocrlf true
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
cache: '%USERPROFILE%\.nuget\packages'
before_build:
- appveyor-retry dotnet restore -v Minimal
build:
  project: CoreCRM.sln
  verbosity: minimal
deploy: off
