# version format
version: 0.1.{build}

# Build worker image (VM template)
image: Visual Studio 2015

# environment variables
environment:
  nodejs_version: "6.9.1"
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

init:
  - git config --global core.autocrlf true
  - ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

# scripts that run after cloning repository
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version

before_build:
  - appveyor-retry dotnet restore -v Minimal

test_script:
  - dotnet test "CoreCRM.IntegrationTest" -c %CONFIGURATION%

cache:
  - '%USERPROFILE%\.nuget\packages'

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration:
  - Debug

# to disable deployment
deploy: off
