version: 0.1.{build}
os: Visual Studio 2017
image: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - master
    - release
clone_depth: 1
skip_tags: true
configuration: Debug
platform: Any CPU
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
cache: '%USERPROFILE%\.nuget\packages'
init:
- cmd: git config --global core.autocrlf true
install:
- ps: dotnet restore -v Minimal
- ps: dotnet add .\Tests\UnitTests\UnitTests.csproj package Appveyor.TestLogger -v 1.0.2-*
build:
  project: CoreCRM.sln
  verbosity: minimal
test_script:
- dotnet test .\Tests\UnitTests\UnitTests.csproj --test-adapter-path:.\Tests\UnitTests --logger:Appveyor
deploy: off
