version: 3.0
image: microsoft/dotnet:latest
env:
    - LANGUAGE=csharp

stages:
    - test

unit_test:
    stage: test
    image: microsoft/dotnet:latest
    env:
        - user=admin
    script:
        - dotnet restore CoreCRM
        - dotnet restore CoreCRM.UnitTest
        - dotnet test ./CoreCRM.UnitTest/CoreCRM.UnitTest.csproj
    pull_request: false

